- name: example tower integration
  hosts: devservers
  tasks:
    - copy:
         content: "Hello World\n"
         dest: /tmp/report

    - name: task2 
      file:
         path: /tmp/abc
         state: directory
         
    - name: task3
      file: path=/tmp/abc2 state=directory
