- name: example tower integration
  hosts: webservers
  tasks:
    - copy:
         content: "Hello World\n"
         dest: /tmp/report

    - name: task2 
      file:
         path: /tmp/abc
         state: directory
